# Generated by Django 5.2.5 on 2025-09-09 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_registro', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida')], max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', 'fecha_hora'], name='asistencia__usuario_84aef5_idx'), models.Index(fields=['tipo_registro'], name='asistencia__tipo_re_5a0600_idx')],
            },
        ),
    ]
