# Generated by Django 5.2.5 on 2025-09-09 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asistencia', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='usuarios.usuario'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['usuario', 'fecha_hora'], name='asistencia__usuario_84aef5_idx'),
        ),
        migrations.AddIndex(
            model_name='registroasistencia',
            index=models.Index(fields=['tipo_registro'], name='asistencia__tipo_re_5a0600_idx'),
        ),
    ]
