# Generated by Django 5.2.5 on 2025-09-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('empleado', 'Empleado'), ('administrador', 'Administrador')], default='empleado', max_length=20),
        ),
    ]
